name = "DyadControlSystems"
uuid = "6f9e59d0-2838-4fee-9bce-c163a6c9592b"
authors = ["Fredrik Bagge Carlson"]
version = "1.1.2"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BlockComponents = "1ef5d832-be8e-447f-9f2c-8b5d17d15fd3"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChebyshevApprox = "17a596ad-87cd-578c-9b6d-01108c31dc04"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ControlSystemIdentification = "3abffc1c-5106-53b7-b354-a47bfc086282"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
ControlSystemsMTK = "687d7614-c7e5-45fc-bfc3-9ee385575c88"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DescriptorSystems = "a81e2ce2-54d1-11eb-2c75-db236b00f339"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DyadInterface = "99806f68-afab-45ca-9d8c-ceff6bc61f54"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
ElectricalComponents = "3fc4c519-469d-4ff5-98c9-d4d06b1514a2"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ForwardDiffChainRules = "c9556dd2-1aed-4cfe-8560-1557cf593001"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowLevelParticleFilters = "d9d29d28-c116-5dba-9239-57a5fe23875b"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PlutoVSCodeApp = "85bbe8c3-d749-40f5-a443-51ce04a145e7"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
RotationalComponents = "824fa3ed-d7dc-4365-8bdf-ac77a1ac2011"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SeeToDee = "1c904df7-48cd-41e7-921b-d889ed9a470c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ADTypes = "1.12.1"
BlockComponents = "2.3.3"
Bumper = "0.6, 0.7"
ChainRules = "1.48"
ChebyshevApprox = "0.4"
Colors = "0.12, 0.13"
CommonSolve = "0.2"
ControlSystemIdentification = "2.10"
ControlSystems = "1.5"
ControlSystemsBase = "1.16.0"
ControlSystemsMTK = "1, 2"
Convex = "0.16"
DSP = "0.7, 0.8"
DataFrames = "1.7.0"
DataInterpolations = "4, 5, 6, 7"
DescriptorSystems = "1"
DiffEqBase = "6"
DifferentiationInterface = "0.6.32"
Distributions = "0.25"
DyadInterface = "4.0.0"
DynamicPolynomials = "0.5, 0.6"
ElectricalComponents = "0.16.3, 0.17"
FillArrays = "1"
FiniteDiff = "2.8"
ForwardDiff = "0.10"
ForwardDiffChainRules = "0.2"
Hypatia = "0.8"
IfElse = "0.1"
Ipopt = "1.0.3"
IterativeSolvers = "0.9"
JSONSchema = "1.4"
JuMP = "1.1"
Juniper = "0.9"
Kronecker = "0.5"
LinearAlgebra = "1.6"
LowLevelParticleFilters = "3.9.1"
Markdown = "1.6"
MathOptInterface = "1.7"
ModelingToolkit = "9.16 - 9.79, 9.80.4"
ModelingToolkitStandardLibrary = "2.3.1"
MonteCarloMeasurements = "1.1"
OSQP = "0.7, 0.8"
Optim = "1"
Optimization = "4"
OptimizationMOI = "0.5"
OptimizationOptimJL = "0.4"
OrdinaryDiffEq = "5, 6"
OrdinaryDiffEqDefault = "1.4.0"
Plots = "1"
PlutoUI = "0.7.37"
PlutoVSCodeApp = "1.1.0"
Polynomials = "3, 4"
PrettyTables = "2.4.0"
Printf = "1.6"
Random = "1.6"
RecipesBase = "1"
Reexport = "1"
RelocatableFolders = "0.1, 0.3, 1"
ResumableFunctions = "1"
RobustAndOptimalControl = "0.4.16"
RotationalComponents = "0.6.4"
RuntimeGeneratedFunctions = "0.5.14"
SciMLBase = "1.63, 2"
SeeToDee = "1"
Serialization = "1.10"
Setfield = "0.7, 0.8, 1"
SparseArrays = "1.6"
StableRNGs = "1.0"
StaticArrays = "1.2"
Statistics = "1.6"
Symbolics = "3.5, 4.3, 5, 6"
ThreadTools = "0.2"
TimerOutputs = "0.5"
UnPack = "1"
julia = "1.6"

[extras]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
QuanserInterface = "d7748c0a-89fb-413b-a9f0-29aba34b281f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataInterpolations", "Plots", "InteractiveUtils", "Markdown", "PlutoUI", "PrettyTables", "Revise", "Pkg"]
